import test from 'node:test';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import { readFileSync,mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../server/app.mjs';
import { validateInitData } from '../server/auth.mjs';
import { openDatabase } from '../server/database.mjs';
import { Service,catalog } from '../server/service.mjs';
import { startOutboxWorker,handleUpdate } from '../server/bot.mjs';
const token='123456789:abcdefghijklmnopqrstuvwxyz_0123456789';
const config=()=>({production:false,botToken:token,botUsername:'gasulvbot',publicUrl:'http://127.0.0.1:3000',webhookSecret:'abcdef0123456789abcdef0123456789abcdef0123456789',dbPath:':memory:',sessionTTL:3600,initDataTTL:3600,adminTelegramIds:['1001'],contactUrl:'https://t.me/gasulvbot'});
function sign(id,extra={},time=Math.floor(Date.now()/1000)) {const p=new URLSearchParams({auth_date:String(time),query_id:`q-${id}`,user:JSON.stringify({id,first_name:'Пользователь '+id}),...extra});const key=createHmac('sha256','WebAppData').update(token).digest();const check=[...p].sort(([a],[b])=>a<b?-1:1).map(([k,v])=>`${k}=${v}`).join('\n');p.set('hash',createHmac('sha256',key).update(check).digest('hex'));return p.toString();}
const jpeg='data:image/jpeg;base64,'+readFileSync(new URL('./fixtures/photo.jpg',import.meta.url)).toString('base64');
const profile=(name,photoId)=>({name,gender:'woman',age:21,course:'3',faculty:catalog.faculties[0],direction:'Архитектура',about:'Люблю город и интересные разговоры.',photoId,consent:true});
async function fixture(t){const cfg=config(),app=createApp(cfg,{botWorker:false});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));cfg.publicUrl=`http://127.0.0.1:${app.server.address().port}`;t.after(()=>app.close());
 async function req(path,method='GET',data,cookie='',origin=cfg.publicUrl){const headers={};if(cookie)headers.Cookie=cookie;if(method!=='GET'&&origin)headers.Origin=origin;if(data!==undefined)headers['Content-Type']='application/json';const res=await fetch(cfg.publicUrl+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data)});const content=res.headers.get('content-type')||'';const result=content.includes('application/json')?await res.json():await res.text();return{status:res.status,data:result,cookie:res.headers.get('set-cookie')?.split(';')[0],headers:res.headers};}
 async function user(id,name){const auth=await req('/api/auth/telegram','POST',{initData:sign(id)});assert.equal(auth.status,200);const photo=await req('/api/photos','POST',{photo:jpeg},auth.cookie);assert.equal(photo.status,201);const p=await req('/api/profile','PUT',profile(name,photo.data.id),auth.cookie);assert.equal(p.status,200);return{cookie:auth.cookie,id:p.data.id,photo:photo.data.id};}
 return{app,cfg,req,user};}
test('Подпись Telegram, давность, подмена, повторные параметры и поле signature',()=>{assert.equal(validateInitData(sign(1001),token).id,1001);assert.equal(validateInitData(sign(1001,{signature:'included-in-hmac'}),token).id,1001);assert.throws(()=>validateInitData(sign(1001).replace('1001','1002'),token));assert.throws(()=>validateInitData(sign(1001,{},Math.floor(Date.now()/1000)-4000),token));assert.throws(()=>validateInitData(sign(1001,{},Math.floor(Date.now()/1000)+100),token));assert.throws(()=>validateInitData(sign(1001)+'&auth_date=1',token));assert.throws(()=>validateInitData('',token));});
test('Пустая база, проверка входа и запрет выдачи серверных файлов',async t=>{const f=await fixture(t);assert.equal(f.app.service.get('SELECT COUNT(*) AS n FROM users').n,0);assert.equal((await f.req('/api/state')).status,401);assert.equal((await f.req('/.env')).status,404);assert.equal((await f.req('/server/config.mjs')).status,404);assert.equal((await f.req('/data/app.sqlite')).status,404);const page=await f.req('/');assert.equal(page.status,200);assert(!page.data.includes('demo'));assert(page.data.includes('telegram-web-app.js'));const js=await f.req('/script.js');assert(!js.data.includes('images.unsplash.com'));assert(!js.data.includes('localStorage'));assert(!js.data.includes('demo-incoming'));const auth=await f.req('/api/auth/telegram','POST',{initData:sign(1001)});assert(auth.headers.get('set-cookie').includes('HttpOnly'));assert(auth.headers.get('set-cookie').includes('SameSite=Lax'));assert.equal((await f.req('/api/state','GET',undefined,auth.cookie)).data.profile,null);assert.equal((await f.req('/api/state','GET',undefined,'gasu_session=forged')).status,401);});
test('Сервер проверяет возраст, факультет, фото, согласие и Origin',async t=>{const f=await fixture(t);const auth=await f.req('/api/auth/telegram','POST',{initData:sign(1001)});const p=await f.req('/api/photos','POST',{photo:jpeg},auth.cookie);const valid=profile('Анна',p.data.id);for(const bad of [{age:17},{age:21.5},{gender:'anything'},{direction:'Чужое направление'},{course:'6'},{about:''},{consent:false},{photoId:'not-owned'}])assert.equal((await f.req('/api/profile','PUT',{...valid,...bad},auth.cookie)).status,400);assert.equal((await f.req('/api/profile','PUT',valid,auth.cookie,'https://evil.example')).status,403);assert.equal((await f.req('/api/photos','POST',{photo:'data:image/svg+xml;base64,AAAA'},auth.cookie)).status,400);assert.equal((await f.req('/api/profile','PUT',valid,auth.cookie)).status,200);const second=await f.user(1002,'Борис');assert.equal((await f.req('/api/profile','PUT',{...valid,photoId:second.photo},auth.cookie)).status,400);assert.equal((await f.req('/api/catalog','GET',undefined,auth.cookie)).data.isAdmin,true);assert.equal(Object.values(catalog.directions).flat().length,54);});
test('Лайки в обе стороны создают один чат и уведомления настоящим участникам',async t=>{const f=await fixture(t),a=await f.user(1001,'Анна'),b=await f.user(1002,'Борис'),c=await f.user(1003,'Вера');const first=await f.req(`/api/people/${b.id}/like`,'POST',undefined,a.cookie);assert.equal(first.data.matched,false);let state=(await f.req('/api/state','GET',undefined,b.cookie)).data;assert.deepEqual(state.incoming,[a.id]);assert.equal(state.notifications[0].type,'like');assert.equal((await f.req(`/api/chats/${a.id}/messages`,'POST',{text:'Без мэтча',clientId:'message-before'},b.cookie)).status,403);
 const results=await Promise.all([f.req(`/api/people/${a.id}/like`,'POST',undefined,b.cookie),f.req(`/api/people/${b.id}/like`,'POST',undefined,a.cookie)]);assert(results.some(r=>r.data.newMatch));assert.equal(f.app.service.get('SELECT COUNT(*) AS n FROM matches').n,1);assert.equal(f.app.service.get('SELECT COUNT(*) AS n FROM likes').n,2);assert.equal((await f.req(`/api/chats/${b.id}/messages`,'GET',undefined,c.cookie)).status,403);state=(await f.req('/api/state','GET',undefined,a.cookie)).data;assert.deepEqual(state.matches,[b.id]);assert(state.chats[b.id]);const feed=(await f.req('/api/feed','GET',undefined,a.cookie)).data.people;assert(!feed.some(p=>p.id===a.id||p.id===b.id));assert.equal((await f.req(`/api/people/${a.id}/like`,'POST',undefined,a.cookie)).status,400);});
test('Сообщения, повторная отправка, непрочитанное и запрет чужого чата',async t=>{const f=await fixture(t),a=await f.user(1001,'Анна'),b=await f.user(1002,'Борис'),c=await f.user(1003,'Вера');f.app.service.like(a.id,b.id);f.app.service.like(b.id,a.id);
 const text='<script>alert(1)</script> Привет!';const data={text,clientId:'stable-client-message'};await f.req(`/api/chats/${b.id}/messages`,'POST',data,a.cookie);const dup=await f.req(`/api/chats/${b.id}/messages`,'POST',data,a.cookie);assert.equal(dup.data.duplicate,true);assert.equal(f.app.service.get('SELECT COUNT(*) AS n FROM messages').n,1);const state=(await f.req('/api/state','GET',undefined,b.cookie)).data;assert(state.chats[a.id].unread);const list=(await f.req(`/api/chats/${a.id}/messages`,'GET',undefined,b.cookie)).data.messages;assert.equal(list[0].text,text);assert.equal(list[0].sender,a.id);await f.req(`/api/chats/${a.id}/read`,'POST',{lastId:list[0].id},b.cookie);assert.equal((await f.req('/api/state','GET',undefined,b.cookie)).data.chats[a.id].unread,false);assert.equal((await f.req(`/api/chats/${b.id}/messages`,'POST',data,c.cookie)).status,403);assert.equal((await f.req(`/api/chats/${a.id}/read`,'POST',{lastId:999999},b.cookie)).status,400);assert.equal((await f.req(`/api/chats/${b.id}/messages`,'POST',{text:' ',clientId:'empty-message'},a.cookie)).status,400);assert(!f.app.service.get("SELECT text FROM outbox WHERE event='message'").text.includes('<script>'));});
test('Подписки без дублей, блокировка, жалобы и удаление данных',async t=>{const f=await fixture(t),a=await f.user(1001,'Анна'),b=await f.user(1002,'Борис');for(let n=0;n<2;n++)await f.req(`/api/people/${b.id}/follow`,'POST',undefined,a.cookie);assert.equal(f.app.service.get('SELECT COUNT(*) AS n FROM follows').n,1);assert.equal((await f.req('/api/state','GET',undefined,b.cookie)).data.followers.length,1);f.app.service.like(a.id,b.id);f.app.service.like(b.id,a.id);f.app.service.sendMessage(a.id,b.id,'Привет','message-id-1');const report=await f.req(`/api/people/${b.id}/report`,'POST',{reason:'Некорректное поведение'},a.cookie);assert.equal(report.status,201);assert.equal((await f.req(`/api/people/${b.id}/block`,'POST',undefined,a.cookie)).status,200);assert.equal(f.app.service.get('SELECT COUNT(*) AS n FROM matches').n,0);assert.equal(f.app.service.get('SELECT COUNT(*) AS n FROM messages').n,0);assert.equal((await f.req(`/api/people/${a.id}/like`,'POST',undefined,b.cookie)).status,404);assert.equal((await f.req(`/api/photos/${a.photo}`,'GET',undefined,b.cookie)).status,404);assert.equal((await f.req('/api/blocks','GET',undefined,a.cookie)).data.people.length,1);await f.req(`/api/people/${b.id}/block`,'DELETE',undefined,a.cookie);assert.equal((await f.req('/api/blocks','GET',undefined,a.cookie)).data.people.length,0);assert.equal((await f.req('/api/account','DELETE',undefined,a.cookie)).status,200);assert.equal((await f.req('/api/state','GET',undefined,a.cookie)).status,401);assert.equal(f.app.service.get('SELECT COUNT(*) AS n FROM photos WHERE user_id=?',a.id).n,0);assert.equal(f.app.service.get('SELECT COUNT(*) AS n FROM sessions WHERE user_id=?',a.id).n,0);});
test('Webhook с секретом, повторные update, /stop и очередь доставки',async t=>{const f=await fixture(t);assert.equal((await f.req('/telegram/webhook','POST',{update_id:1})).status,403);const update={update_id:10,message:{chat:{id:1001,type:'private'},from:{id:1001,first_name:'Анна'},text:'/start'}};let response=await fetch(f.cfg.publicUrl+'/telegram/webhook',{method:'POST',headers:{'Content-Type':'application/json','X-Telegram-Bot-Api-Secret-Token':f.cfg.webhookSecret},body:JSON.stringify(update)});assert.equal(response.status,200);await response.json();handleUpdate(f.app.service,update);assert.equal(f.app.service.get('SELECT COUNT(*) AS n FROM outbox').n,1);const calls=[];const worker=startOutboxWorker(f.app.service,async(config,method,data)=>{calls.push({method,data});return true;});try{await worker.tick();assert.equal(calls.length,1);assert.equal(calls[0].data.reply_markup.inline_keyboard[0][0].web_app.url,f.cfg.publicUrl);assert.equal(f.app.service.get('SELECT COUNT(*) AS n FROM outbox').n,0);handleUpdate(f.app.service,{...update,update_id:11,message:{...update.message,text:'/stop'}});assert.equal(f.app.service.get('SELECT push_enabled FROM users WHERE telegram_id=?','1001').push_enabled,0);await worker.tick();assert.equal(calls.length,2);}finally{worker.stop();}});
test('Модерация доступна только администратору, забаненная сессия закрывается',async t=>{const f=await fixture(t),a=await f.user(1001,'Админ'),b=await f.user(1002,'Борис');assert.equal((await f.req('/api/admin/reports','GET',undefined,b.cookie)).status,403);assert.equal((await f.req('/api/admin/ban','POST',{userId:b.id,banned:true},a.cookie)).status,200);assert.equal((await f.req('/api/state','GET',undefined,b.cookie)).status,401);assert.equal((await f.req('/api/auth/telegram','POST',{initData:sign(1002)})).status,403);assert.equal((await f.req('/api/admin/ban','POST',{userId:a.id,banned:true},a.cookie)).status,400);handleUpdate(f.app.service,{update_id:123,message:{chat:{id:1002,type:'private'},from:{id:1002},text:'/start'}});assert(f.app.service.get('SELECT 1 FROM bot_updates WHERE id=123'));});
test('API и соединение событий доступны только владельцу сессии',async t=>{const f=await fixture(t),a=await f.user(1001,'Анна'),b=await f.user(1002,'Борис');const abort=new AbortController();const stream=await fetch(f.cfg.publicUrl+'/api/events',{headers:{Cookie:b.cookie},signal:abort.signal});assert.equal(stream.status,200);const reader=stream.body.getReader();const decoder=new TextDecoder();assert(decoder.decode((await reader.read()).value).includes('connected'));await f.req(`/api/people/${b.id}/like`,'POST',undefined,a.cookie);const event=decoder.decode((await reader.read()).value);assert(event.includes('event: state'));abort.abort();assert.equal((await f.req('/api/events')).status,401);});
test('База сохраняется при перезапуске, фото не меняется до сохранения анкеты',()=>{const dir=mkdtempSync(join(tmpdir(),'gasulv-test-'));try{const path=join(dir,'app.sqlite'),cfg=config();let db=openDatabase(path),service=new Service(db,cfg);const u=service.register({id:1001,first_name:'Анна'}),p=service.uploadPhoto(u.id,jpeg);service.updateProfile(u.id,profile('Анна',p.id));const staged=service.uploadPhoto(u.id,jpeg);assert.equal(service.user(u.id).photo_id,p.id);assert(service.photo(p.id,u.id));db.close();db=openDatabase(path);service=new Service(db,cfg);assert.equal(service.user(u.id).name,'Анна');assert.equal(service.user(u.id).photo_id,p.id);service.updateProfile(u.id,profile('Анна',staged.id));assert.throws(()=>service.photo(p.id,u.id));assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');db.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('Bearer-доступ работает без cookies для Telegram Web, фото остаются закрытыми',async t=>{const f=await fixture(t),a=await f.user(1001,'Анна');const auth=await f.req('/api/auth/telegram','POST',{initData:sign(1001)});assert.match(auth.data.sessionToken,/^[A-Za-z0-9_-]{43}$/);const headers={Authorization:'Bearer '+auth.data.sessionToken};const state=await fetch(f.cfg.publicUrl+'/api/state',{headers});assert.equal(state.status,200);assert.equal((await state.json()).profile.id,a.id);const photo=await fetch(f.cfg.publicUrl+`/api/photos/${a.photo}`,{headers});assert.equal(photo.status,200);assert.equal(photo.headers.get('content-type'),'image/jpeg');assert((await photo.arrayBuffer()).byteLength>100);assert.equal((await f.req(`/api/photos/${a.photo}`)).status,401);const change=await fetch(f.cfg.publicUrl+'/api/settings',{method:'PUT',headers:{...headers,'Content-Type':'application/json',Origin:f.cfg.publicUrl},body:JSON.stringify({visible:false,pushEnabled:false})});assert.equal(change.status,200);});
test('История сообщений выдаётся страницами без потери, скрытую анкету можно отписать',async t=>{const f=await fixture(t),a=await f.user(1001,'Анна'),b=await f.user(1002,'Борис');f.app.service.like(a.id,b.id);f.app.service.like(b.id,a.id);for(let i=0;i<110;i++)f.app.service.sendMessage(a.id,b.id,'Сообщение '+i,'client-'+i);const latest=(await f.req(`/api/chats/${a.id}/messages`,'GET',undefined,b.cookie)).data.messages;assert.equal(latest.length,100);const earlier=(await f.req(`/api/chats/${a.id}/messages?before=${latest[0].id}`,'GET',undefined,b.cookie)).data.messages;assert.equal(earlier.length,10);assert.equal(new Set([...earlier,...latest].map(x=>x.id)).size,110);f.app.service.follow(a.id,b.id,true);f.app.service.settings(b.id,{visible:false,pushEnabled:false});assert.equal((await f.req(`/api/people/${b.id}/follow`,'DELETE',undefined,a.cookie)).status,200);assert.equal((await f.req(`/api/people/${b.id}`,'GET',undefined,a.cookie)).status,404);assert.equal((await f.req(`/api/chats/${b.id}/messages`,'GET',undefined,a.cookie)).status,200);});
test('Очередь повторяет временные сбои и отключает отправку заблокировавшему бота',async t=>{const cfg=config(),db=openDatabase(':memory:'),service=new Service(db,cfg),u=service.register({id:1001,first_name:'Анна'});t.after(()=>db.close());service.run('UPDATE users SET bot_chat_id=? WHERE id=?','1001',u.id);service.run('INSERT INTO outbox(target,text,event,next_at,created_at) VALUES(?,?,?,?,?)',u.id,'Уведомление','like',Date.now(),Date.now());let code=429;const worker=startOutboxWorker(service,async()=>{const e=new Error();e.telegramCode=code;e.retryAfter=2;throw e;});t.after(()=>worker.stop());await worker.tick();assert.equal(service.get('SELECT attempts FROM outbox').attempts,1);service.run('UPDATE outbox SET next_at=0');code=403;await worker.tick();assert.equal(service.get('SELECT COUNT(*) AS n FROM outbox').n,0);assert.equal(service.user(u.id).push_enabled,0);assert.equal(service.user(u.id).bot_chat_id,null);});
