import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function client(){const nodes=new Map();const make=()=>({innerHTML:'',textContent:'',className:'',hidden:false,style:{},dataset:{},isConnected:false,value:'',scrollTop:0,scrollHeight:0,clientHeight:0,offsetWidth:350,classList:{add(){},remove(){},toggle(){},contains(){return false;}},addEventListener(){},setAttribute(){},removeAttribute(){},querySelector(){return make()},querySelectorAll(){return[]},focus(){},showModal(){this.open=true},close(){this.open=false;}});const document={hidden:false,querySelector(key){if(!nodes.has(key))nodes.set(key,make());return nodes.get(key);},querySelectorAll(){return[]},addEventListener(){}};
 const ctx=vm.createContext({document,window:{},console,URLSearchParams,URL,AbortSignal,Date,Math,Map,Set,Number,String,JSON,encodeURIComponent,setInterval(){},setTimeout(){},clearTimeout(){}});
 const source=readFileSync(new URL('../script.js',import.meta.url),'utf8').replace(/boot\(\);\s*$/,'');vm.runInContext(source,ctx);return{run:code=>vm.runInContext(code,ctx),nodes};}
const data="({id:'c9510d36-8616-4080-9c69-44c62c3bc539',name:'<img src=x onerror=alert(1)>',gender:'woman',age:21,course:'3',faculty:FACULTIES[0],direction:'Архитектура',about:'<script>alert(1)</script>',photo:'/api/photos/c9510d36-8616-4080-9c69-44c62c3bc539',tags:['<svg onload=x>'],followers:0,likes:0})";
test('Клиентские экраны экранируют имена и описания, тестовой панели нет',()=>{const c=client();c.run(`const fixture=${data};state.profile=fixture;PEOPLE=[fixture];feedPeople=[fixture];renderDiscover()`);let html=c.nodes.get('#screen').innerHTML;assert(html.includes('&lt;img'));assert(html.includes('&lt;script'));assert(!html.includes('<script>'));assert(!html.includes('<svg onload=x>'));assert(html.includes('data-photo="/api/photos/'));c.run("state.matches=[fixture.id];state.chats[fixture.id]={messages:[],unread:false};renderChats()");html=c.nodes.get('#screen').innerHTML;assert(html.includes('&lt;img'));assert(!html.includes('<img src=x'));c.run('renderProfile()');html=c.nodes.get('#screen').innerHTML;assert(html.includes('Подписчики'));assert(!html.includes('demo'));assert(!html.includes('Gold'));});
test('Анкета требует возраст, курс, связанное направление, описание и своё фото',()=>{const c=client();c.run("draft=newDraft();step=0");assert(c.run('validateDraftStage()'));c.run("draft={...draft,name:'Иван',gender:'man',age:'17'}");assert(c.run('validateDraftStage()'));c.run("draft.age='21'");assert.equal(c.run('validateDraftStage()'),'');c.run("step=1;draft.course='Магистратура';draft.faculty=FACULTIES[0];draft.direction='Архитектура'");assert.equal(c.run('validateDraftStage()'),'');c.run('draft.faculty=FACULTIES[1]');assert(c.run('validateDraftStage()'));c.run("step=2;draft.about='Описание';draft.photo=''");assert(c.run('validateDraftStage()'));c.run("draft.photo='/api/photos/example';renderOnboarding()");const html=c.nodes.get('#screen').innerHTML;assert(html.includes('id="consent"'));assert(html.includes('id="photo-input"'));assert(!html.includes('тестовое'));});

test('HTML корректно подключает клиентский скрипт',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.match(html,/<script src="script\.js"><\/script>/);assert.equal((html.match(/<script\b/g)||[]).length,(html.match(/<\/script>/g)||[]).length);});
