import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { ApiError } from './auth.mjs';
import { validateJpeg } from './image.mjs';
import { transaction } from './database.mjs';
export const catalog=JSON.parse(readFileSync(new URL('../catalog.json',import.meta.url),'utf8'));
const now=()=>Date.now();
export class Service {
 constructor(db,config,publish=()=>{}){this.db=db;this.config=config;this.publish=publish;}
 get(sql,...params){return this.db.prepare(sql).get(...params);} all(sql,...params){return this.db.prepare(sql).all(...params);} run(sql,...params){return this.db.prepare(sql).run(...params);}
 user(id){const u=this.get('SELECT * FROM users WHERE id=?',id);if(!u)throw new ApiError(404,'Пользователь не найден');if(u.banned)throw new ApiError(403,'Доступ к аккаунту ограничен');return u;}
 register(tg){const date=now(),existing=this.get('SELECT * FROM users WHERE telegram_id=?',String(tg.id));const name=String(tg.first_name||'').slice(0,80),username=String(tg.username||'').slice(0,80);
 if(existing){this.run('UPDATE users SET telegram_name=?,username=? WHERE id=?',name,username,existing.id);return this.user(existing.id);}
 const id=randomUUID();this.run('INSERT INTO users(id,telegram_id,telegram_name,username,created_at,updated_at) VALUES(?,?,?,?,?,?)',id,String(tg.id),name,username,date,date);return this.user(id);
 }
 blocked(a,b){return !!this.get('SELECT 1 FROM blocks WHERE (source=? AND target=?) OR (source=? AND target=?)',a,b,b,a);}
 publicProfile(u){return {id:u.id,name:u.name,gender:u.gender,age:u.age,course:u.course,faculty:u.faculty,direction:u.direction,about:u.about,photo:u.photo_id?`/api/photos/${u.photo_id}`:'',tags:[u.faculty, u.course==='Магистратура'?'Магистратура':`${u.course} курс`],followers:this.get('SELECT COUNT(*) AS n FROM follows WHERE target=?',u.id).n,likes:this.get('SELECT COUNT(*) AS n FROM likes WHERE target=?',u.id).n};}
 profile(id,viewer){const u=this.user(id);if(!u.name||!u.photo_id||(!u.visible&&id!==viewer)||this.blocked(id,viewer))throw new ApiError(404,'Анкета недоступна');return this.publicProfile(u);}
 ready(id){const u=this.user(id);if(!u.name||!u.photo_id)throw new ApiError(409,'Сначала заполните анкету');return u;}
 target(viewer,id){this.ready(viewer);if(viewer===id)throw new ApiError(400,'Нельзя выбрать свою анкету');const u=this.user(id);if(!u.name||!u.photo_id||!u.visible||this.blocked(viewer,id))throw new ApiError(404,'Анкета недоступна');return u;}
 validateProfile(data){for(const key of ['name','gender','course','faculty','direction','about'])if(typeof data[key]!=='string')throw new ApiError(400,'Заполните все поля анкеты');if(!data.name.trim()||data.name.trim().length>40)throw new ApiError(400,'Имя: от 1 до 40 символов');if(!['man','woman'].includes(data.gender))throw new ApiError(400,'Выберите пол');if(!Number.isInteger(data.age)||data.age<18||data.age>100)throw new ApiError(400,'Возраст: целое число от 18 до 100');if(!['1','2','3','4','5','Магистратура'].includes(data.course))throw new ApiError(400,'Выберите курс');if(!catalog.faculties.includes(data.faculty)||!catalog.directions[data.faculty].includes(data.direction))throw new ApiError(400,'Направление не соответствует факультету');if(!data.about.trim()||data.about.trim().length>500)throw new ApiError(400,'Описание: от 1 до 500 символов');if(data.consent!==true)throw new ApiError(400,'Подтвердите условия публикации анкеты');}
 updateProfile(id,data){this.validateProfile(data);const old=this.user(id);const photoId=data.photoId||old.photo_id;if(!photoId||!this.get('SELECT 1 FROM photos WHERE id=? AND user_id=?',photoId,id))throw new ApiError(400,'Загрузите фото');this.run('UPDATE users SET name=?,gender=?,age=?,course=?,faculty=?,direction=?,about=?,photo_id=?,consent_at=COALESCE(consent_at,?),updated_at=? WHERE id=?',data.name.trim(),data.gender,data.age,data.course,data.faculty,data.direction,data.about.trim(),photoId,now(),now(),id);this.run('DELETE FROM photos WHERE user_id=? AND id<>?',id,photoId);this.publish(id,'state');return this.publicProfile(this.user(id));}
 uploadPhoto(id,data){this.user(id);if(typeof data!=='string'||!/^data:image\/jpeg;base64,[A-Za-z0-9+/]+=*$/.test(data))throw new ApiError(400,'Загрузите JPEG-фото через приложение');const bytes=Buffer.from(data.split(',')[1],'base64');validateJpeg(bytes);const idPhoto=randomUUID();this.run('INSERT INTO photos(id,user_id,mime,data,created_at) VALUES(?,?,?,?,?)',idPhoto,id,'image/jpeg',bytes,now());return{id:idPhoto,url:`/api/photos/${idPhoto}`};}
 photo(id,viewer){const p=this.get('SELECT p.*,u.name,u.visible,u.banned FROM photos p JOIN users u ON u.id=p.user_id WHERE p.id=?',id);if(!p||(p.user_id!==viewer&&(!p.name||!p.visible||p.banned||this.blocked(viewer,p.user_id))))throw new ApiError(404,'Фото недоступно');return p;}
 notification(target,actor,type,text){this.run('INSERT INTO notifications(target,actor,type,text,created_at) VALUES(?,?,?,?,?)',target,actor,type,text,now());this.run('INSERT INTO outbox(target,actor,text,event,next_at,created_at) VALUES(?,?,?,?,?,?)',target,actor,text,type,now(),now());}
 like(source,target){const me=this.ready(source);this.target(source,target);let matched=false,newMatch=false;transaction(this.db,()=>{const inserted=this.run('INSERT OR IGNORE INTO likes(source,target,created_at) VALUES(?,?,?)',source,target,now()).changes;this.run('DELETE FROM skips WHERE source=? AND target=?',source,target);if(inserted)this.notification(target,source,'like',`${me.name} нравится ваша анкета ♥`);if(this.get('SELECT 1 FROM likes WHERE source=? AND target=?',target,source)){const [a,b]=[source,target].sort();const r=this.run('INSERT OR IGNORE INTO matches(id,user_a,user_b,created_at) VALUES(?,?,?,?)',randomUUID(),a,b,now());matched=true;newMatch=!!r.changes;if(newMatch){this.notification(target,source,'match','У вас взаимная симпатия! Чат уже открыт.');this.notification(source,target,'match','У вас взаимная симпатия! Чат уже открыт.');}}});this.publish(source,'state');this.publish(target,newMatch?'match':'state',{personId:source});return{matched,newMatch};}
 skip(source,target){this.target(source,target);this.run('INSERT OR IGNORE INTO skips VALUES(?,?)',source,target);return{ok:true};}
 follow(source,target,enabled){const me=this.ready(source);if(enabled)this.target(source,target);transaction(this.db,()=>{if(enabled){const added=this.run('INSERT OR IGNORE INTO follows VALUES(?,?,?)',source,target,now()).changes;if(added)this.notification(target,source,'follow',`${me.name} подписался(ась) на вас`);}else this.run('DELETE FROM follows WHERE source=? AND target=?',source,target);});this.publish(source,'state');this.publish(target,'state');return{ok:true};}
 feed(id,gender='all',faculty='all'){this.ready(id);if(!['all','man','woman'].includes(gender)||!(faculty==='all'||catalog.faculties.includes(faculty)))throw new ApiError(400,'Неверный фильтр');return this.all(`SELECT u.* FROM users u WHERE u.id<>? AND u.name IS NOT NULL AND u.photo_id IS NOT NULL AND u.visible=1 AND u.banned=0 AND (?='all' OR u.gender=?) AND (?='all' OR u.faculty=?) AND NOT EXISTS(SELECT 1 FROM likes WHERE source=? AND target=u.id) AND NOT EXISTS(SELECT 1 FROM skips WHERE source=? AND target=u.id) AND NOT EXISTS(SELECT 1 FROM blocks WHERE (source=? AND target=u.id) OR (target=? AND source=u.id)) ORDER BY u.created_at DESC LIMIT 60`,id,gender,gender,faculty,faculty,id,id,id,id).map(u=>this.publicProfile(u));}
 matchFor(a,b){const [x,y]=[a,b].sort();const m=this.get('SELECT * FROM matches WHERE user_a=? AND user_b=?',x,y);if(!m||this.blocked(a,b))throw new ApiError(403,'Чат доступен только при взаимной симпатии');this.user(b);return m;}
 chatMessages(a,b,before=null){this.ready(a);const m=this.matchFor(a,b);const rows=before?this.all('SELECT * FROM messages WHERE match_id=? AND id<? ORDER BY id DESC LIMIT 100',m.id,before):this.all('SELECT * FROM messages WHERE match_id=? ORDER BY id DESC LIMIT 100',m.id);return rows.reverse().map(r=>({id:r.id,sender:r.sender===a?'me':b,text:r.text,time:r.created_at,clientId:r.client_id}));}
 sendMessage(a,b,text,clientId){this.ready(a);const m=this.matchFor(a,b);if(typeof text!=='string'||!text.trim()||text.trim().length>2000)throw new ApiError(400,'Сообщение: от 1 до 2000 символов');if(typeof clientId!=='string'||!/^[a-zA-Z0-9_-]{8,80}$/.test(clientId))throw new ApiError(400,'Неверный идентификатор сообщения');let inserted=false;transaction(this.db,()=>{inserted=!!this.run('INSERT OR IGNORE INTO messages(match_id,sender,client_id,text,created_at) VALUES(?,?,?,?,?)',m.id,a,clientId,text.trim(),now()).changes;if(inserted)this.notification(b,a,'message','Вам пришло новое сообщение');});this.publish(a,'message',{personId:b});this.publish(b,'message',{personId:a});return{ok:true,duplicate:!inserted};}
 readChat(a,b,lastId){const m=this.matchFor(a,b);if(!Number.isInteger(lastId)||lastId<0||lastId>(this.get('SELECT COALESCE(MAX(id),0) AS n FROM messages WHERE match_id=?',m.id).n))throw new ApiError(400,'Неверная отметка прочтения');this.run('INSERT INTO chat_reads VALUES(?,?,?) ON CONFLICT(match_id,user_id) DO UPDATE SET last_id=MAX(last_id,excluded.last_id)',m.id,a,lastId);this.publish(a,'state');return{ok:true};}
 snapshot(id){const u=this.user(id);const own=u.name&&u.photo_id?this.publicProfile(u):null;const people=new Map();const relations=(table,col,other)=>this.all(`SELECT u.* FROM ${table} r JOIN users u ON u.id=r.${other} WHERE r.${col}=? AND u.name IS NOT NULL AND u.banned=0`,id).filter(p=>!this.blocked(id,p.id)).map(p=>{people.set(p.id,this.publicProfile(p));return p.id;});const likes=relations('likes','source','target'),incoming=relations('likes','target','source'),following=relations('follows','source','target'),followers=relations('follows','target','source');const matches=[],chats={};for(const m of this.all('SELECT * FROM matches WHERE user_a=? OR user_b=?',id,id)){const other=m.user_a===id?m.user_b:m.user_a;const p=this.get('SELECT * FROM users WHERE id=? AND banned=0',other);if(!p||this.blocked(id,other))continue;matches.push(other);people.set(other,this.publicProfile(p));const last=this.get('SELECT * FROM messages WHERE match_id=? ORDER BY id DESC LIMIT 1',m.id),lastRead=this.get('SELECT last_id FROM chat_reads WHERE match_id=? AND user_id=?',m.id,id)?.last_id||0;chats[other]={messages:last?[{id:last.id,sender:last.sender===id?'me':other,text:last.text,time:last.created_at}]:[],unread:!!this.get('SELECT 1 FROM messages WHERE match_id=? AND sender<>? AND id>? LIMIT 1',m.id,id,lastRead)};}
 const notifications=this.all('SELECT * FROM notifications WHERE target=? ORDER BY id DESC LIMIT 100',id).filter(n=>!this.blocked(id,n.actor)).map(n=>{const p=this.get('SELECT * FROM users WHERE id=?',n.actor);if(p?.name&&!p.banned)people.set(p.id,this.publicProfile(p));return{id:n.id,type:n.type,personId:n.actor,text:n.text,time:n.created_at,read:!!n.is_read};});return{profile:own,likes,incoming,following,followers,matches,chats,notifications,people:[...people.values()],settings:{pushEnabled:!!u.push_enabled,visible:!!u.visible},telegramName:u.telegram_name};}
 readNotifications(id,maxId){if(!Number.isSafeInteger(maxId)||maxId<0)throw new ApiError(400,'Неверный номер уведомления');this.run('UPDATE notifications SET is_read=1 WHERE target=? AND id<=?',id,maxId);this.publish(id,'state');return{ok:true};}
 block(a,b){this.ready(a);this.user(b);if(a===b)throw new ApiError(400,'Нельзя заблокировать себя');transaction(this.db,()=>{this.run('INSERT OR IGNORE INTO blocks VALUES(?,?,?)',a,b,now());this.run('DELETE FROM follows WHERE (source=? AND target=?) OR (source=? AND target=?)',a,b,b,a);this.run('DELETE FROM likes WHERE (source=? AND target=?) OR (source=? AND target=?)',a,b,b,a);this.run('DELETE FROM matches WHERE (user_a=? AND user_b=?) OR (user_a=? AND user_b=?)',a,b,b,a);this.run('DELETE FROM notifications WHERE (target=? AND actor=?) OR (target=? AND actor=?)',a,b,b,a);this.run('DELETE FROM outbox WHERE (target=? AND actor=?) OR (target=? AND actor=?)',a,b,b,a);});this.publish(a,'state');this.publish(b,'state');return{ok:true};}
 blockedList(id){return this.all('SELECT u.* FROM blocks b JOIN users u ON u.id=b.target WHERE b.source=?',id).map(u=>this.publicProfile(u));}
 unblock(a,b){this.run('DELETE FROM blocks WHERE source=? AND target=?',a,b);this.publish(a,'state');return{ok:true};}
 report(a,b,reason){this.ready(a);this.user(b);if(a===b||typeof reason!=='string'||reason.trim().length<3||reason.length>1000)throw new ApiError(400,'Опишите причину жалобы (3–1000 символов)');if(this.get('SELECT 1 FROM reports WHERE source=? AND target=? AND created_at>?',a,b,now()-3600000))throw new ApiError(429,'Жалоба уже принята');this.run('INSERT INTO reports(source,target,reason,created_at) VALUES(?,?,?,?)',a,b,reason.trim(),now());return{ok:true};}
 deleteUser(id){transaction(this.db,()=>this.run('DELETE FROM users WHERE id=?',id));this.publish(id,'deleted');for(const u of this.all('SELECT id FROM users'))this.publish(u.id,'state');return{ok:true};}
 settings(id,data){if(typeof data.pushEnabled!=='boolean'||typeof data.visible!=='boolean')throw new ApiError(400,'Неверные настройки');this.run('UPDATE users SET push_enabled=?,visible=? WHERE id=?',Number(data.pushEnabled),Number(data.visible),id);this.publish(id,'state');return{ok:true};}
}
